package com.emergency.domain;

public enum TimelineEventType {
    // Phase 1-2
    INCIDENT_CREATED,
    INCIDENT_INJECTED,
    TRAFFIC_CHANGED,
    SERVICE_DEGRADED,
    ERROR_RATE_INCREASED,
    LATENCY_INCREASED,
    INCIDENT_ACTIVE,
    INCIDENT_RESET,
    INCIDENT_RESOLVED,

    // Phase 3
    INVESTIGATION_STARTED,
    ROOT_CAUSE_IDENTIFIED,

    // Phase 4 — Remediation
    REMEDIATION_PROPOSED,
    SAFETY_CHECK_STARTED,
    SAFETY_CHECK_PASSED,
    SAFETY_CHECK_FAILED,
    APPROVAL_REQUESTED,
    ACTION_APPROVED,
    ACTION_REJECTED,
    ACTION_BLOCKED,
    ACTION_EXECUTING,
    ACTION_EXECUTED,
    ACTION_FAILED,
    VERIFICATION_STARTED,
    VERIFICATION_PASSED,
    VERIFICATION_FAILED,
    REINVESTIGATION_STARTED,
    INCIDENT_ESCALATED,
    ROLLBACK_EXECUTED
}
